### ISSUE TITLE
net/http SSL_connect error

### ISSUE THREAD

**Issue by mattbailey** [pixeltrix/prowler#1]
Just using this with a basic script:

```
/usr/lib/ruby/1.9.1/net/http.rb:799:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
        from /usr/lib/ruby/1.9.1/net/http.rb:799:in `block in connect'
        from /usr/lib/ruby/1.9.1/timeout.rb:68:in `timeout'
        from /usr/lib/ruby/1.9.1/timeout.rb:99:in `timeout'
        from /usr/lib/ruby/1.9.1/net/http.rb:799:in `connect'
        from /usr/lib/ruby/1.9.1/net/http.rb:755:in `do_start'
        from /usr/lib/ruby/1.9.1/net/http.rb:744:in `start'
        from /usr/lib/ruby/gems/1.9.1/gems/prowler-1.3.1/lib/prowler/application.rb:173:in `perform_request'        
        from /usr/lib/ruby/gems/1.9.1/gems/prowler-1.3.1/lib/prowler/application.rb:159:in `perform_post'
        from /usr/lib/ruby/gems/1.9.1/gems/prowler-1.3.1/lib/prowler/application.rb:106:in `perform'        
        from /usr/lib/ruby/gems/1.9.1/gems/prowler-1.3.1/lib/prowler/application.rb:69:in `notify'
        from /usr/lib/ruby/gems/1.9.1/gems/prowler-1.3.1/lib/prowler.rb:78:in `notify'
        from notify.rb:12:in `block in <main>'
        from notify.rb:7:in `each'
        from notify.rb:7:in `<main>'
```

**Comment by pixeltrix** [comment]
You're getting a verification error on the Prowl SSL certificate which indicates that your Ruby's OpenSSL library isn't picking up the system supplied certificates. Can you try this script and see what you get:

``` ruby
require 'net/https'

cacert = <<-EOF
-----BEGIN CERTIFICATE-----
MIIDIDCCAomgAwIBAgIENd70zzANBgkqhkiG9w0BAQUFADBOMQswCQYDVQQGEwJVUzEQMA4GA1UE
ChMHRXF1aWZheDEtMCsGA1UECxMkRXF1aWZheCBTZWN1cmUgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
MB4XDTk4MDgyMjE2NDE1MVoXDTE4MDgyMjE2NDE1MVowTjELMAkGA1UEBhMCVVMxEDAOBgNVBAoT
B0VxdWlmYXgxLTArBgNVBAsTJEVxdWlmYXggU2VjdXJlIENlcnRpZmljYXRlIEF1dGhvcml0eTCB
nzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEAwV2xWGcIYu6gmi0fCG2RFGiYCh7+2gRvE4RiIcPR
fM6fBeC4AfBONOziipUEZKzxa1NfBbPLZ4C/QgKO/t0BCezhABRP/PvwDN1Dulsr4R+AcJkVV5MW
8Q+XarfCaCMczE1ZMKxRHjuvK9buY0V7xdlfUNLjUA86iOe/FP3gx7kCAwEAAaOCAQkwggEFMHAG
A1UdHwRpMGcwZaBjoGGkXzBdMQswCQYDVQQGEwJVUzEQMA4GA1UEChMHRXF1aWZheDEtMCsGA1UE
CxMkRXF1aWZheCBTZWN1cmUgQ2VydGlmaWNhdGUgQXV0aG9yaXR5MQ0wCwYDVQQDEwRDUkwxMBoG
A1UdEAQTMBGBDzIwMTgwODIyMTY0MTUxWjALBgNVHQ8EBAMCAQYwHwYDVR0jBBgwFoAUSOZo+SvS
spXXR9gjIBBPM5iQn9QwHQYDVR0OBBYEFEjmaPkr0rKV10fYIyAQTzOYkJ/UMAwGA1UdEwQFMAMB
Af8wGgYJKoZIhvZ9B0EABA0wCxsFVjMuMGMDAgbAMA0GCSqGSIb3DQEBBQUAA4GBAFjOKer89961
zgK5F7WF0bnj4JXMJTENAKaSbn+2kmOeUJXRmm/kEd5jhW6Y7qj/WsjTVbJmcVfewCHrPSqnI0kB
BIZCe/zuf6IWUrVnZ9NA2zsmWLIodz2uFHdh1voqZiegDfqnc1zqcPGUIWVEX/r87yloqaKHee95
70+sB3c4
-----END CERTIFICATE-----
EOF

File.open('/tmp/cacert.pem', 'w'){ |f| f.write(cacert) }

http = Net::HTTP.new('api.prowlapp.com', 443)
http.use_ssl = true
http.verify_mode = OpenSSL::SSL::VERIFY_PEER
http.ca_file = "/tmp/cacert.pem"

http.start do
  begin
    request = Net::HTTP::Get.new('/publicapi/verify?apikey=efb8500cdac51acf5055f849c768b740e881b11c', {})
    response = http.request(request)

    if response.is_a?(Net::HTTPSuccess)
      puts "Prowl Success: #{response.class}"
    else
      puts "Prowl Failure: #{response.class}"
    end

    puts response.body
  rescue TimeoutError
    puts "Timeput whilst contacting the Prowl server"
  end
end
```

Also what platform, ruby version and openssl version do you have?

**Comment by mattbailey** [comment]
```
Prowl Success: Net::HTTPOK
<?xml version="1.0" encoding="UTF-8"?>
  <prowl>
  <success code="200" remaining="999" resetdate="1342806617" />
</prowl>
```

Yeah, I figured it should be a simple cert issue, but I'm using ubuntu server 12.04, ruby 1.9.3p0 (2011-10-30 revision 33570) [x86_64-linux], openssl 1.0.1-4ubuntu5.2, I'd assume that's all recent enough to have all the CAs

**Comment by pixeltrix** [comment]
You have three options:
1. If you're using Prowler within a Rails app take the key out of the above script and put it in `config/cacert.pem`.
2. If you're using Prowler within another framework or standalone script then take the key out of the above script, put it in a file somewhere accessible and configure Prowler to use it by:
   
   ``` ruby
   Prowler.configure do |config|
     config.root_certificates = "path/to/cert.pem"
   end
   
   # or
   
   Prowler.root_certificates = "path/to/cert.pem"
   ```
3. Install the ca-certificates package and set SSL_CERT_FILE in your environment:
   
   ``` sh
   $ sudo apt-get install ca-certificates && sudo dpkg-reconfigure ca-certificates
   $ export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
   ```
   
   If you don't want to configure OpenSSL to use them by default then you can configure Prowler to use them:
   
   ``` ruby
   Prowler.configure do |config|
     config.root_certificates = "/etc/ssl/certs/ca-certificates.crt"
   end
   
   # or
   
   Prowler.root_certificates = "/etc/ssl/certs/ca-certificates.crt"
   ```

If you're using ubuntu server then it's likely that ca-certificates is already installed so you just need to export the `SSL_CERT_FILE` variable. It's interesting that the default ubuntu ruby package doesn't use the system certificates by default - I use rvm locally and [Brightbox's packages](https://launchpad.net/~brightbox/+archive/ruby-ng) on my servers and they both pick them up automatically.

**Comment by tritter** [comment]
I got the same error tested everything above... No fix! I really don't know where to debug I use the Backup gem it implements this gem!

[2012/12/07 09:45:15][error]   An Error occured which has caused this Backup to abort before completion.
[2012/12/07 09:45:15][error]   Reason: OpenSSL::SSL::SSLError
[2012/12/07 09:45:15][error]   SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
[2012/12/07 09:45:15][error] 

[2012/12/07 09:45:15][error]   /home/deployer/apps/roosterapp/shared/bundle/ruby/1.9.1/gems/prowler-1.3.1/lib/prowler/application.rb:173:in `perform_request'
[2012/12/07 09:45:15][error]   /home/deployer/apps/roosterapp/shared/bundle/ruby/1.9.1/gems/prowler-1.3.1/lib/prowler/application.rb:159:in`perform_post'
[2012/12/07 09:45:15][error]   /home/deployer/apps/roosterapp/shared/bundle/ruby/1.9.1/gems/prowler-1.3.1/lib/prowler/application.rb:106:in `perform'
[2012/12/07 09:45:15][error]   /home/deployer/apps/roosterapp/shared/bundle/ruby/1.9.1/gems/prowler-1.3.1/lib/prowler/application.rb:69:in`notify'
[2012/12/07 09:45:15][error]   /home/deployer/apps/roosterapp/shared/bundle/ruby/1.9.1/gems/backup-3.0.27/lib/backup/notifier/prowl.rb:60:in `send_message'
[2012/12/07 09:45:15][error]   /home/deployer/apps/roosterapp/shared/bundle/ruby/1.9.1/gems/backup-3.0.27/lib/backup/notifier/prowl.rb:55:in`notify!'
[2012/12/07 09:45:15][error]   /home/deployer/apps/roosterapp/shared/bundle/ruby/1.9.1/gems/backup-3.0.27/lib/backup/notifier/base.rb:60:in `perform!'
[2012/12/07 09:45:15][error]   /home/deployer/apps/roosterapp/shared/bundle/ruby/1.9.1/gems/backup-3.0.27/lib/backup/model.rb:259:in`each'
[2012/12/07 09:45:15][error]   /home/deployer/apps/roosterapp/shared/bundle/ruby/1.9.1/gems/backup-3.0.27/lib/backup/model.rb:259:in `perform!'
[2012/12/07 09:45:15][error]   /home/deployer/apps/roosterapp/shared/bundle/ruby/1.9.1/gems/backup-3.0.27/lib/backup/cli/utility.rb:74:in`block in perform'
[2012/12/07 09:45:15][error]   /home/deployer/apps/roosterapp/shared/bundle/ruby/1.9.1/gems/backup-3.0.27/lib/backup/cli/utility.rb:65:in `each'
[2012/12/07 09:45:15][error]   /home/deployer/apps/roosterapp/shared/bundle/ruby/1.9.1/gems/backup-3.0.27/lib/backup/cli/utility.rb:65:in`perform'
[2012/12/07 09:45:15][error]   /home/deployer/apps/roosterapp/shared/bundle/ruby/1.9.1/gems/thor-0.16.0/lib/thor/task.rb:27:in `run'
[2012/12/07 09:45:15][error]   /home/deployer/apps/roosterapp/shared/bundle/ruby/1.9.1/gems/thor-0.16.0/lib/thor/invocation.rb:120:in`invoke_task'
[2012/12/07 09:45:15][error]   /home/deployer/apps/roosterapp/shared/bundle/ruby/1.9.1/gems/thor-0.16.0/lib/thor.rb:275:in `dispatch'
[2012/12/07 09:45:15][error]   /home/deployer/apps/roosterapp/shared/bundle/ruby/1.9.1/gems/thor-0.16.0/lib/thor/base.rb:425:in`start'
[2012/12/07 09:45:15][error]   /home/deployer/apps/roosterapp/shared/bundle/ruby/1.9.1/gems/backup-3.0.27/bin/backup:11:in `<top (required)>'
[2012/12/07 09:45:15][error]   /home/deployer/apps/roosterapp/shared/bundle/ruby/1.9.1/bin/backup:23:in`load'
[2012/12/07 09:45:15][error]   /home/deployer/apps/roosterapp/shared/bundle/ruby/1.9.1/bin/backup:23:in `<main>'

**Comment by pixeltrix** [comment]
@tritter is this in production or on your development machine?

**Comment by tritter** [comment]
On my production machine 12.04 ubuntu, with openssl 1.0.1. On my mac (developement machine) it's working!

I put already this on top of my .bashrc: export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt 
And installed the latest with:

```
sudo apt-get install ca-certificates && sudo dpkg-reconfigure ca-certificates
```

**Comment by pixeltrix** [comment]
I have seen `SSL_CERT_FILE` fail to work in certain circumstances - for example Heroku's OpenSSL seems to ignore it. Try the following in a initializer:

``` ruby
Prowler.configure do |config|
  config.root_certificates = ENV['SSL_CERT_FILE'] if ENV['SSL_CERT_FILE']
end
```

**Comment by tritter** [comment]
Thank you very much that did it!!

For others with the same problem (in the backup gem) put in the ~/Backup/config.rb:

```
Backup::Dependency.load('prowler')
Prowler.configure do |config|
config.root_certificates = ENV['SSL_CERT_FILE'] if ENV['SSL_CERT_FILE']
end
```

**Comment by pixeltrix** [comment]
Looks like there are other dependencies in Backup that are susceptible to the same problem - it should probably configure it globally itself.
