### ISSUE TITLE
SSL errors verifying Prowl's certificate

### ISSUE THREAD

**Issue by VxJasonxV** [pixeltrix/prowler#3]
I tried to use this gem to send some messages via Prowl, but doing so led to an SSL error both locally as well as on Heroku:

``` plain
2015-01-20T11:36:13.990929+00:00 heroku[scheduler.6882]: State changed from starting to up
2015-01-20T11:36:15.960697+00:00 app[scheduler.6882]:   from /app/vendor/ruby-2.1.4/lib/ruby/2.1.0/net/http.rb:852:in `start'
2015-01-20T11:36:15.960672+00:00 app[scheduler.6882]: /app/vendor/ruby-2.1.4/lib/ruby/2.1.0/net/http.rb:920:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
2015-01-20T11:36:15.960698+00:00 app[scheduler.6882]:   from /app/vendor/bundle/ruby/2.1.0/gems/prowler-1.3.1/lib/prowler/application.rb:173:in `perform_request'
2015-01-20T11:36:15.960695+00:00 app[scheduler.6882]:   from /app/vendor/ruby-2.1.4/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
2015-01-20T11:36:15.960694+00:00 app[scheduler.6882]:   from /app/vendor/ruby-2.1.4/lib/ruby/2.1.0/net/http.rb:920:in `connect'
2015-01-20T11:36:15.960705+00:00 app[scheduler.6882]:   from notifier.rb:13:in `<main>'
2015-01-20T11:36:15.960699+00:00 app[scheduler.6882]:   from /app/vendor/bundle/ruby/2.1.0/gems/prowler-1.3.1/lib/prowler/application.rb:159:in `perform_post'
2015-01-20T11:36:15.960689+00:00 app[scheduler.6882]:   from /app/vendor/ruby-2.1.4/lib/ruby/2.1.0/net/http.rb:920:in `block in connect'
2015-01-20T11:36:15.960703+00:00 app[scheduler.6882]:   from /app/vendor/bundle/ruby/2.1.0/gems/prowler-1.3.1/lib/prowler/application.rb:106:in `perform'
2015-01-20T11:36:15.960692+00:00 app[scheduler.6882]:   from /app/vendor/ruby-2.1.4/lib/ruby/2.1.0/timeout.rb:101:in `call'
2015-01-20T11:36:15.960690+00:00 app[scheduler.6882]:   from /app/vendor/ruby-2.1.4/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
2015-01-20T11:36:15.960704+00:00 app[scheduler.6882]:   from /app/vendor/bundle/ruby/2.1.0/gems/prowler-1.3.1/lib/prowler/application.rb:69:in `notify'
2015-01-20T11:36:15.960693+00:00 app[scheduler.6882]:   from /app/vendor/ruby-2.1.4/lib/ruby/2.1.0/timeout.rb:101:in `timeout'
2015-01-20T11:36:16.815052+00:00 heroku[scheduler.6882]: Process exited with status 1
2015-01-20T11:36:16.831644+00:00 heroku[scheduler.6882]: State changed from up to complete
```

I even tried passing `verify_certificate: false` into the initialization parameters ( https://github.com/pixeltrix/prowler/blob/29931ce04336cc58f45732af00f33b5821cda431/lib/prowler/configuration.rb#L7 ), but that didn't seem to make a difference.

Is this because trusted roots are required to be implemented? ( https://github.com/pixeltrix/prowler/blob/29931ce04336cc58f45732af00f33b5821cda431/lib/prowler/configuration.rb#L47-L57 )

I'm not using this in a rails app. I could easily find a certificate bundle and create it at that path, but why is this a requirement?

**Comment by HeikoBornholdt** [comment]
I've the same problem. Do you found a solution?

**Comment by VxJasonxV** [comment]
When this gem failed, I switched to [ruby-prowl](https://github.com/augustl/ruby-prowl) instead.

**Comment by HeikoBornholdt** [comment]
Okay, I’ve switched to prowly.
